### ISSUE TITLE
Sub stats and Video Player size

### ISSUE THREAD

**Issue by bentenz5** [tgicn/NightcoreIssues#1]
The video player is MASSIVE! I would like a way to make the video player look and work like plug's did.

Also, Subcriber stats! I miss my golden crown and extended features!

Thanks

**Comment by TigerFlo** [comment]
Hello, for the video size for the moment look at this : http://prntscr.com/8l78yl and i'm not the staff but i think : this website is not plug don't forget it so it's why you don't have golden crown

**Comment by ECPinoy** [comment]
that's true: this is NOT plug in ANY way, although we try to make it similar to plug.  Another thing to note is that this is barely in ALPHA stage, don't expect much other than music and chat. More work will be done in the future, including what we'll do with donations, subscribers, RCS integration, and vanity features.

**Comment by bentenz5** [comment]
I know, its just a request is all.......

**Comment by enteryournamehere** [comment]
The site you see is the full site. There are no features to give you for being a plug sub...

**Comment by TheBloodMerchant** [comment]
Pretty sure for the size they should add two options kinda like on youtube, so just have a variable set as the x and y and have a default value set for them, then using a button set that to a certain amount

**Comment by enteryournamehere** [comment]
@TheBloodMerchant We'll add an option to choose the size of the video soon

**Comment by Foorack** [comment]
Option to resize the video have been implemented by ... someone. :smile:
