### ISSUE TITLE
Greys and ResDJs can see deleted chat.

### ISSUE THREAD

**Issue by tranquillite** [tgicn/NightcoreIssues#10]
So, apparently, greys and res djs can see deleted chat.

<3
- quilly-sama

**Comment by Foorack** [comment]
Thanks for reporting it. Will investigate it. :)

**Comment by tgicn** [comment]
This is an issue that was caused by the changes when new ranks were added. This should be a simple frontend change.

**Comment by tgicn** [comment]
This issue has been fixed and will be patched in the next update.
