### ISSUE TITLE
Signup With Email

### ISSUE THREAD

**Issue by TheBloodMerchant** [tgicn/NightcoreIssues#13]
This site would be much better in terms of bans and spam, as well as server space if you had to use a valid email address to signup. maybe you enter an email, server sends you a code you enter it and it verifies.

**Comment by Foorack** [comment]
Or that after you created your user there would be a place where you can enter and validate your email. If not verified it will be removed in X days or so. The possibilities of all the different paths on this subject is many...

**Comment by oDeathwingo** [comment]
also adding the ability to signup via social sites like youtube/twitter and/or facebook would be nice..
it would remove the hassle of signing in and confirming e-mail every time

**Comment by tgicn** [comment]
We are implementing a different way to prevent spams in the next update
