### ISSUE TITLE
Suggestion for Leaving Playlist

### ISSUE THREAD

**Issue by Grengras** [tgicn/NightcoreIssues#16]
Would it be possible to have the "Join Waitlist" button toggle into a "Leave Waitlist" button for people currently on the waiting list?

There seems to be a lot of people who want to leave for various reasons and that should do it.

**Comment by bentenz5** [comment]
Yes. Please do this. I really want to be able to swap songs out if I happen to put in the wrong link and realize it.

**Comment by Foorack** [comment]
Nice idea. Its on our to do list now. :smiley:

**Comment by bentenz5** [comment]
Epic!

**Comment by Foorack** [comment]
Completed. Will be on the site next time its updated.
