### ISSUE TITLE
Suggestion for a possible Alternative / LinkIn to a History list

### ISSUE THREAD

**Issue by Grengras** [tgicn/NightcoreIssues#17]
Currently the Waitlist shows all current DJ's waiting in order, and the song they chose is locked in. Since the video used is already locked in would it be possible to change the waiting list to a two column list - with the dj name on the left, and the youtube v=? on the right column.

This suggestion combined with my earlier Leave Waitlist toggle suggestion would allow people to avoid duplicating a recently played song, and not have to wait through the entire djlist until their turn came around again.

**Comment by bentenz5** [comment]
Dude, you are on fire. You've got some good suggestions and I hope they get implemented! :)

**Comment by tgicn** [comment]
This was already considered before releasing to the public. This feature will not be implemented as we will be changing over to playlists soon.
