### ISSUE TITLE
Automatically detect if song is recently played

### ISSUE THREAD

**Issue by gyroninja** [tgicn/NightcoreIssues#18]
Now that we have our own site would it be possible to just check if the song they have selected to play has been played recently. Would also be handy if it didn't just check if it was an exact match but that might produce more false positives / other problems.

**Comment by Zombosaur** [comment]
Adding to this, would it be possible to check if the song they choose is on the blacklist too?

**Comment by enteryournamehere** [comment]
This won't be added before playlists are implemented

**Comment by tgicn** [comment]
This has been added
