### ISSUE TITLE
Volume bar  overlaps username field

### ISSUE THREAD

**Issue by ahrPopeye** [tgicn/NightcoreIssues#2]
https://gyazo.com/665e0a5a026001aee924177bc494f8e0
As you can see in the images there is a overposition of the volume and the username to login.

**Comment by TigerFlo** [comment]
Yeah, maybe optimized for Chrome : 
Firefox : http://prntscr.com/8l7ld2 
Chrome : http://prntscr.com/8l7lnf

**Comment by Foorack** [comment]
The website should work the same in both Chrome and Firefox. This is a visual glitch and is on our to do list to fix.

**Comment by WindWalk12** [comment]
I think it's because the volume isn't at a fixed position, as it moves around when you make your window smaller.

Pictures:
http://i.imgur.com/gmwmKeN.png
http://i.imgur.com/UTeZ0Mi.png

**Comment by WindWalk12** [comment]
It's fixed now and will be in the update that comes in 3 mins :D
