### ISSUE TITLE
Two mute options

### ISSUE THREAD

**Issue by MeNotFound** [tgicn/NightcoreIssues#21]
so like was in plug i would glad to see an option when u simply clickl on the current volume level without moving it . change it to 0% and when u click it again it will return to the last value it was
i liked to sometimes watch youtube stuff and its rly nice when u can simply mute the music by pressing on the volume without actualy changing it and once u done press it again and its back to the 20% or 50% it was before
i would rly like to get that option like i used in plug so tnx u!

and the second thing its the snooze buttom that we all liked to get

**Comment by WindWalk12** [comment]
I totally feel you on this one! :D

**Comment by Grengras** [comment]
Snooze is definitely missed. Everyone has different tastes and I try to never begrudge anyone else's musical choices... but being able to just click one button, then tab away and check my mail or something else until the music returns is a feature I didn't realize I cared about until it was gone.

**Comment by RX14** [comment]
:+1: for the click to mute volume while i watch something else.

**Comment by Foorack** [comment]
Snoozed have been implemented. A mute button is planned.

**Comment by tgicn** [comment]
This has been implemented for 2 versions now
