### ISSUE TITLE
Add a button for the blacklists

### ISSUE THREAD

**Issue by armyunleashed** [tgicn/NightcoreIssues#23]
Can you add a button the sends you to a page with all of the blacklisted songs. It helps to know what you can't play so you aren't skipped. Just a suggestion. Sorry if i put this in the wrong location. Wasn't sure where else to say it.

**Comment by Foorack** [comment]
You put this in the right location. :) I edited your answer a bit to make it clearer as currently the blacklist isn't public.

**Comment by Foorack** [comment]
It have come to my knowledge that a command for this is already implemented. If you want to see the blacklist regarding the different themes you can do "!op" in chat. :smiley: Will mark this as closed now.
