### ISSUE TITLE
Special wallpapers for background

### ISSUE THREAD

**Issue by oDeathwingo** [tgicn/NightcoreIssues#24]
I saw this idea on the chat and waited for it to hit here.. since there was no sign of it after couple of hours Im writing for him/her (owner of the idea) now
The barebone idea consists of setting special backgrounds per user.. but the idea goes on more
when a user plays a video you can see his current wallpaper (if he wants to share) and apply if you want
or auto apply so your wallpaper will change on each song like a real disco
one bad point would be +18 or troll images being in backgrounds.. but those users would be directly banned
if there is a ban system implemented?

**Comment by oDeathwingo** [comment]
umm if you do hate the [] tags behind requests/bug reports you can tell to me.. I thought it would ease your guys' jobs for finding what you want

**Comment by Foorack** [comment]
@oDeathwingo I rather use the label system built into Github instead. :smiley:

**Comment by gyroninja** [comment]
@oDeathwingo The inappropriate backgrounds could probably go under the same rules as "offtopic" music / videos. Though if you blacklisted an image would we still have the video still play (if the video is not blacklisted) or would we just skip it altogether.

**Comment by Foorack** [comment]
Sorry for the delay on this one. This has been discussed between the developers and it was decided that it would be too much work to implement taking into account that it is not a much-requested feature nor would have any real purpose. The site is about listening to Nightcore and that is where we would like to focus our time on. If you think you have any reasonable argument to why we still should implement it then please respond to this issue and I will open it again.
