### ISSUE TITLE
Join/Leave waitlist button doesnt toggle back after leaving.

### ISSUE THREAD

**Issue by bentenz5** [tgicn/NightcoreIssues#28]
Hello,

The waitlist doesnt go back to "Join Waitlist" after you leave the waitlist.

Not a massive bug, but I thought I would report it anyway.

Thanks,
-CSxKING, who uses his ultra old github account.

Update: Now it seems to be the oposite (after the patch).
Once you hit spot 1, it swaps to join waitlist even if you haven't played yet.

Image: http://i.imgur.com/iTpFc7g.png

**Comment by Foorack** [comment]
It does for me. When you say "after you leave the waitlist", do you mean after you played?

**Comment by Foorack** [comment]
Fixed.

**Comment by bentenz5** [comment]
Thanks lad
