### ISSUE TITLE
Doesn't work on IE9

### ISSUE THREAD

**Issue by TigerFlo** [tgicn/NightcoreIssues#3]
Hello, the website doesn't work on IE9 (i don't use IE but for thoose who use it, it give http://prntscr.com/8l7n28)

**Comment by Foorack** [comment]
I am in no position to make any final decision however as it currently stands implementing IE9 support is low priority. IE9 lacks alot of features the new site is build upon and its highly recommended to upgrade to Edge (or switch to Firefox or Chrome).

**Comment by TheBloodMerchant** [comment]
I'm pretty sure nothing works on Internet Explorer. It's being phased out by firefox and chrome.
