### ISSUE TITLE
problem with sound?

### ISSUE THREAD

**Issue by nao-kimaji** [tgicn/NightcoreIssues#33]
having 100% volume on the site gives it a weak "tz" every so often, alrady tested having it at 50% and its a ton better, 

ok, my pc volume is at 10%, and having the site volume at 100% makes weak "tz" in the sound... wile having it at 50% i just turned pc vulume up to 100%  instead of 10%, and it dosnt make that sound ONCE. ( but damn the sound was loud at 100% xD )

but as it says in title, Problem with sound"?". anyone else noticing?
-----------------------------------------------------------------------------------------
but atleast i know for shure its not a problem with my headset. 

(the sound "tz" only comes when the song hits a spesific "tone", and do not appear in every song.(and when it hits the area where the "tone" is, its just so frustrating..., but atleast its easy to deal with ;) )

**Comment by Foorack** [comment]
Will mark this as unconfirmed until at least one more can confirm it. I can't test it out right now as I am not close a computer. :)

**Comment by gyroninja** [comment]
I'm not getting this issue. Maybe it's just a problem with your speakers / sound setup? @nao-kimaji Does this happen with the regular player on youtube.com?

**Comment by Foorack** [comment]
Seven days have now passed without anyone else confirming this issue. Please respond to this issue if it ever happens again and I will gladly open the Issue again. :+1:
