### ISSUE TITLE
Site Won't Load Properly On Firefox

### ISSUE THREAD

**Issue by Rhinovex** [tgicn/NightcoreIssues#34]
I don't know why but, one day the site just started to act up and nothing related to chat/waitlist/people online loaded and the current video kept starting over every 3 seconds. I'm also unable to login, this is what it looks like: http://i.imgur.com/RrzZmYR.png

I could simply run it on Chrome but, I'm really ocd about having everything in the same place and I don't feel like switching back over to Chrome after having issues on other websites and being used to Firefox.

**Comment by TigerFlo** [comment]
strange, it's ok for me : http://prntscr.com/8n1zno (on firefox too)

**Comment by enteryournamehere** [comment]
Can be fixed by running Firefox as administrator. It should just be fine without that, but hey at least it works now ^^
