### ISSUE TITLE
Waitlist number.

### ISSUE THREAD

**Issue by nao-kimaji** [tgicn/NightcoreIssues#35]
would like to get a number of people in the waitlist without clicking "waitlist" as it says on "users"

**Comment by Foorack** [comment]
This is now being worked on. Thanks for submitting it. ^^

Also, there is no need in writing "Suggestion", that's what we have tags for. :smirk:

**Comment by tgicn** [comment]
This has been implemented for the next release

**Comment by nao-kimaji** [comment]
nice

2015-11-19 17:25 GMT+01:00 Christopher Nelson <notifications@github.com>:
