### ISSUE TITLE
I Pressing Charges

### ISSUE THREAD

**Issue by FEKtacularProblems** [tgicn/NightcoreIssues#37]
I was on this new website of yours and i stubbed my toe on your website. im in so much pain and my medication is so expensive. i demand that you get this over with and pay me my lap dance before i bring this to court and ask for 420 trillion dollars. ill give you 24 hours to comply, after 24 hours i will hunt you down and tell your mom. ive never lost a court case before so yal should be pretty damn scared about my threats. youre all horrible poeple making such a dangerous website.i hope all of you stub your toes and go through the pain im in now. YOUVE BEEN WARNED!

**Comment by Foorack** [comment]
Locked for troll. Gratz on being the first.... -.-
