### ISSUE TITLE
Video starts over when I refresh the page

### ISSUE THREAD

**Issue by ko0j** [tgicn/NightcoreIssues#4]
I am using waterfox and when I refresh the page the video that was playing starts from the beginning.

**Comment by swaqrazzer** [comment]
Having same on chrome :)

**Comment by Zombosaur** [comment]
happened to me too on chrome

**Comment by Foorack** [comment]
Can't seem to reproduce on Chrome...

**Comment by gyroninja** [comment]
Happened on firefox 41

**Comment by Foorack** [comment]
Ok, will look into in once I get home.

**Comment by Foorack** [comment]
Tried it myself on latest Firefox and was not able to reproduce. :disappointed: 

I will leave this open for a few days so if it happens to other people then they should be able to report as well. If this doesn't happen again I will conclude that the bug has been fixed.

**Comment by bentenz5** [comment]
Might be the OS that causes it. I know it does it on my Chromebook from time to time. I use a Lenovo N21 Chromebook provided by my School.

**Comment by minymind** [comment]
Hey, i also noticed that once. think it isn't that a big problem (my opinion).
Firefox 42.0b2 (beta) also happened once i wasn't using the beta.
also tried it with water fox (after like 20 refreshes) still works fine for me.
so might want to retry it yourself x3

**Comment by Foorack** [comment]
This just happened to me as well. Will look into it. :+1:

**Comment by enteryournamehere** [comment]
Can confirm on Google Chrome version 45.0.2454.99 m

**Comment by Foorack** [comment]
Raised the priority of this as its happening multiple time to several people.

**Comment by tgicn** [comment]
Old bug. Was fixed during past updates
