### ISSUE TITLE
chat links

### ISSUE THREAD

**Issue by ferminuno** [tgicn/NightcoreIssues#40]
when someone write sometimes the chat put a link on the text, something like this "http://yup..das".

and other links didn't work (like this: http://nightcore-331.net/viewtopic.php?f=31&t=1637&sid=1db69e7c82d615638bec4baccaf43347) don't know why, i tried writing it whit www. and without it

Here a pic from what happens in the chat: http://i.imgur.com/vV2bPKF.png

**Comment by bentenz5** [comment]
I believe a fix is in the works, but I could be wrong.....

**Comment by tgicn** [comment]
This has been fixed in the latest update
