### ISSUE TITLE
Chat bug and volume bug

### ISSUE THREAD

**Issue by Haykke** [tgicn/NightcoreIssues#42]
Hey guys, nice wokr with the new update, its growing prety good, dou a rly annoying bug now happens wich is wehn I put the volume of the music down to 0 and it ends and starts other music the volume goes back to where it was before, and this bug too less anoying but just to let u know http://prntscr.com/8plghh
Best regards and good job

**Comment by TheLoliKing** [comment]
I 2nd this bug report.

The music starts again after every video/song swap, even if you turn the volume down to 0%, and if you press "Mute" on the video, everything seems to be useless when the next song/video plays.

**Comment by Foorack** [comment]
This has been fixed and the patch will be live next time the sites updates.
