### ISSUE TITLE
Report an Issue Does Not Fit in Menu

### ISSUE THREAD

**Issue by gyroninja** [tgicn/NightcoreIssues#43]
See -> https://gyazo.com/c37bd3b29c48e24a322a2a25202e4729

Happens on both my desktop and mobile device. I'm running firefox on both.

**Comment by WindWalk12** [comment]
Hey

Is it possible you can give some more details.

1. Your resolution?

I tried in my own Firefox and it doesn't happen in there.

**Comment by Foorack** [comment]
@gyroninja Could you post a screenshot of it happening on your phone?

**Comment by gyroninja** [comment]
It seems to no longer happen on my phone.

**Comment by Foorack** [comment]
@gyroninja Ok. Does it still happen on your desktop?

**Comment by gyroninja** [comment]
@Foorack Yes

**Comment by WindWalk12** [comment]
@gyroninja Still bugging?

**Comment by gyroninja** [comment]
@WindWalk12 Yep

**Comment by gyroninja** [comment]
Are we worried about this still considering we changed the menu for the christmas theme? If we are going to revert back to the old theme we should fix it still.

**Comment by tgicn** [comment]
The menu wasnt changed specifically for the christmas theme. The new menu will stay for the foreseeable future therefore this issue should be closed
