### ISSUE TITLE
Remove your own messages

### ISSUE THREAD

**Issue by bentenz5** [tgicn/NightcoreIssues#46]
Heyo,

So today I goofed and posted something I wasnt supposed to in chat.

Users, RDJ and grey should be able to remove theyre own messages in the future, but only if from them, and not anyone elses. This would prevent such mishaps.

Thanks,
-CSxKING, RDJ

**Comment by Foorack** [comment]
This is a feature I missed over at plug.dj as well...

**Comment by tgicn** [comment]
This is the intended way of this working
