### ISSUE TITLE
Faster menu animation

### ISSUE THREAD

**Issue by nao-kimaji** [tgicn/NightcoreIssues#47]
its so irriating that the menu animationg is so slow. if u miss click u need 2 wait a bit more then needed. make it easyer by making the animation faster, and it takes less time for the person clicking it to do he's/her's buseniss ;)

**Comment by nao-kimaji** [comment]
its still somewhat fast, but its still to slow :\

**Comment by enteryournamehere** [comment]
You don't have to click on the menu you only have to hover it so idk what you mean with miss clicking

**Comment by Foorack** [comment]
I also think it is a little slow to be honest.
