### ISSUE TITLE
[BUG] User suggestion box in chat when mentionning people

### ISSUE THREAD

**Issue by Nuvm** [tgicn/NightcoreIssues#49]
![alt text](http://i.imgur.com/D64ZezU.png "Chat suggestion bug 1")
![alt text](http://i.imgur.com/ZN8ppwW.png "Chat suggestion bug 2")

should explain everything.
a little bit of css/js should fix it

**Comment by BSRxX5NAKEXx** [comment]
Appears to be fixed in the latest update.
