### ISSUE TITLE
shift + tab breaks things (chrome)

### ISSUE THREAD

**Issue by Zombosaur** [tgicn/NightcoreIssues#53]
accidentally pressed shift + tab, resulting in this http://prntscr.com/90ekty

**Comment by tgicn** [comment]
I have tried multiple times on many browsers (mainly different chrome versions) but cannot reproduce this issue.

**Comment by bentenz5** [comment]
I can confirm this happens from time to time but very rarely. I mean VERY rarely. Usually if Chrome is outdated or corrupted somehow.

**Comment by bentenz5** [comment]
Uhm.... Sorry about that, just realized this was closed.
