### ISSUE TITLE
[Suggestion] General website improvements

### ISSUE THREAD

**Issue by Aekami** [tgicn/NightcoreIssues#57]
***Account creation improvement(s)***
  - When creating an account, maybe create a password confirmation box, checking if both passwords are the same. This would prevent typos when typing the password, thus not being able to acces the account afterwards.

***Song in history indicator/sign***

  - Maybe adding an indicator of some sort next to "Active song" would be handy, allowing to easily see whether or not the song the user wants to play is in history. 
Or an alternative would be to turn the "Active song" red to the user if the song is still in history.

**Comment by enteryournamehere** [comment]
Good suggestions! The second one is already implemented, when you select a
song that's in history you get an alert. It doesn't check in the waitlist
though currently

**Comment by tgicn** [comment]
The first part of this is already being implemented as part of the new profile system. Thank you for your suggestions.
