### ISSUE TITLE
Adding Song to Playlist Redirects

### ISSUE THREAD

**Issue by gyroninja** [tgicn/NightcoreIssues#59]
When I add a song from the search feature to a playlist it redirects my browser.

**Comment by bentenz5** [comment]
Are you clicking on the thumbnail or the actual title?

**Comment by gyroninja** [comment]
It happens when I drag the title to the playlist on the sidebar.

**Comment by enteryournamehere** [comment]
Known bug on Firefox.

**Comment by tgicn** [comment]
Fixed in latest update
