### ISSUE TITLE
Snooze Does Not Function Correctly

### ISSUE THREAD

**Issue by gyroninja** [tgicn/NightcoreIssues#61]
Snooze does not appear to be deactivated after a song ends. When I hit unsnooze it does not restore the volume but keep it at 0%.

**Comment by bentenz5** [comment]
Yeah that happens. Its kinda annoying, and if not fixed in the next update, I might try to fix it myself and put that fix in NCS....

**Comment by BSRxX5NAKEXx** [comment]
Appears to be fixed in the latest update. 
When it comes out of snooze it restores the volume to the percent it was before the snooze/mute it does not directly set it to 100%.

**Comment by gyroninja** [comment]
This bug is not yet fixed. Even if you just double click the snooze / unsnooze it gets turned down to 0% and does not get turned back up.

**Comment by BSRxX5NAKEXx** [comment]
This has been fixed in the next update now.
