### ISSUE TITLE
Can't Add Songs From Youtube Search

### ISSUE THREAD

**Issue by gyroninja** [tgicn/NightcoreIssues#62]
When I search for songs with youtube search it does not let me drag the song anymore.

**Comment by tgicn** [comment]
Please could you give us some more information like Browser, OS, etc?

**Comment by gyroninja** [comment]
Firefox: 42.0+build2-0ubuntu0.15.10.1
Kubuntu: Linux NINJA-5 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gyroninja** [comment]
This was fixed with the latest update.
