### ISSUE TITLE
User stats (Level, xp, etc) do not show up at all when logged in at two locations.

### ISSUE THREAD

**Issue by bentenz5** [tgicn/NightcoreIssues#66]
Heyo,

It appears if you have the same account logged in at two locations your level, xp, and the progress bar do not show up.

The progress bar will be where your name and level usually are, and have absolutely nothing in it. Not even -/- or 0/0. It'll just be blank.

**Comment by BSRxX5NAKEXx** [comment]
Fixed in next update.
