### ISSUE TITLE
Firefox scroll iseu

### ISSUE THREAD

**Issue by minymind** [tgicn/NightcoreIssues#7]
the website wont scale with firefox since i can scrol slightly up and down with firefox.
just a smal thing tough ;3
Resolution: 1920 x 1080

**Comment by Foorack** [comment]
Sorry, but I dont really understand the problem. Could you post a screenshot of when it fails to scale? :)

**Comment by minymind** [comment]
If you open firefox and scroll at the video the site scrols a small bit. you should test it out ;3

**Comment by Foorack** [comment]
Will try once I get home.

**Comment by minymind** [comment]
hey, been commenting on the wrong post..... x3
but since you maby saw it tough ill still post it here...
I already have the latest update. even tried the beta.
made a video from it (might be a bit hard to notice)
https://www.youtube.com/watch?v=QCvz_bKmcyk&feature=youtu.be

**Comment by Foorack** [comment]
A patch have been made and it should be fixed next time the website gets updated. :smiley:

**Comment by Foorack** [comment]
@minymind Reopened as the fix didn't work on all screen sizes.

**Comment by minymind** [comment]
awhh to bad
hope it will get fixed soon ;3

**Comment by minymind** [comment]
@Foorack it is gone btw ;3 the new update fixed it (for me)
even when i am minimizing it xd
ty!! ;D

**Comment by Foorack** [comment]
:+1:
