### ISSUE TITLE
Make Current DJ one line

### ISSUE THREAD

**Issue by gyroninja** [tgicn/NightcoreIssues#75]
If you take a look at https://i.gyazo.com/1aee33ff00391e2bae6cf6d1476b990a.png you can notice DJ and the DJ's name overlaps the video. I think the site would look better if you made it all on one line.

If we make it one line https://i.gyazo.com/5573e2177b10180c9e96a4ce3ecf9d35.png it looks a lot better.

**Comment by tgicn** [comment]
This is a strange one as it is designed to be all on 1 line. Do you have anything that would alter the site or are you zoomed in?

Anything that could affect the size of the text?

**Comment by WindWalk12** [comment]
I think the font is different

**Comment by gyroninja** [comment]
I'm not zoomed in at all. I haven't manually changed any font settings to my browser.

**Comment by gyroninja** [comment]
This issue is now resolved
