### ISSUE TITLE
Not Changing Song

### ISSUE THREAD

**Issue by TheBloodMerchant** [tgicn/NightcoreIssues#8]
I dc'd for about 5secs then reconnected, i know cause i was playing HS, and when i reconnected it continued playing till the end of the song then just froze there.
Thanks In Advance

**Comment by Foorack** [comment]
Must have been some internet problems on your end. Only way that could've happened is if the YouTube player had buffered the rest of the video and the site didn't manage to connect back.

Please comment here to re-open the issue if it happens again though. <3
