### ISSUE TITLE
Weird connection issue

### ISSUE THREAD

**Issue by Ar3nn** [tgicn/NightcoreIssues#9]
A friend I tried inviting to the new community got walled out by an error stating this string:
Error: EMFILE, open 'C:\Users\Administrator\nightcore\NightcoreDJ\public\index.html'
    at Error (native)
Any ideas?

**Comment by Foorack** [comment]
This was caused by some server issues we had around the time you posted this. The server issues have been fixed so you should no longer see that error message. If you still continue to experience the problem, please respond here and I will reopen this issue.
